# Generated by Django 4.1.4 on 2023-01-07 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pqc', '0008_alter_custompqcjob_id'),
        ('evaluate', '0005_alter_testjob_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='customCircuitJob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_pqc.custompqcjob'),
        ),
        migrations.AlterField(
            model_name='testjob',
            name='pqc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
