# Generated by Django 2.2.14 on 2023-01-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0006_testjob_customcircuitjob_alter_testjob_pqc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjob',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
