# Generated by Django 4.1.4 on 2023-01-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pqc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompqcjob',
            name='ansatz',
            field=models.CharField(choices=[('RealAmplitudes', 'RealAmplitudes'), ('EfficientSU2', 'EfficientSU2'), ('TwoLocal', 'TwoLocal')], default='RealAmplitudes', max_length=30),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='ansatz_entanglement',
            field=models.TextField(default='full'),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='ansatz_entanglement_blocks',
            field=models.TextField(default='cx'),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='ansatz_reps',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='ansatz_rotation_blocks',
            field=models.TextField(default="['ry', 'rz']"),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='ansatz_skip_final_rotation_layer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='ansatz_skip_unentangled_qubits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='ansatz_su2_gates',
            field=models.TextField(default="['ry', 'y']"),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='encoder',
            field=models.CharField(choices=[('ZFeatureMap', 'ZFeatureMap'), ('ZZFeatureMap', 'ZZFeatureMap'), ('PauliFeatureMap', 'PauliFeatureMap'), ('NLocal', 'NLocal')], default='ZFeatureMap', max_length=30),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='encoder_alpha',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='encoder_entanglement',
            field=models.TextField(default='full'),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='encoder_entanglement_blocks',
            field=models.TextField(default='cx'),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='encoder_paulis',
            field=models.TextField(default="['Z', 'ZZ']"),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='encoder_reps',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='encoder_rotation_blocks',
            field=models.TextField(default="['ry', 'rz']"),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='encoder_skip_final_rotation_layer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='path_hist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custompqcjob',
            name='path_qc_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
