# Generated by Django 2.2.14 on 2023-01-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pqc', '0004_custompqcjob_kl_div_custompqcjob_mw_meas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompqcjob',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
