# Generated by Django 2.2.14 on 2023-01-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_pqc', '0008_alter_custompqcjob_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompqcjob',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
