# Generated by Django 2.2.14 on 2022-12-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epochs', models.IntegerField(default='50')),
                ('n_samples', models.IntegerField(default='100')),
                ('batch_size', models.IntegerField(default='32')),
                ('learning_rate', models.FloatField(default=0.001)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=15)),
                ('result_path', models.TextField(blank=True, null=True)),
                ('loss_string', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
