# Generated by Django 2.2.14 on 2022-12-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainjob',
            name='model',
            field=models.TextField(default='HAE'),
        ),
        migrations.AddField(
            model_name='trainjob',
            name='pqc',
            field=models.TextField(default='1'),
        ),
    ]
