# Generated by Django 2.2.14 on 2023-01-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_trainjob_initial_point_trainjob_is_binary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainjob',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
