# Generated by Django 4.1.4 on 2023-01-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_auto_20230107_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainjob',
            name='pqc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
