# Generated by Django 2.2.14 on 2023-01-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_alter_trainjob_id_alter_trainjob_pqc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.TextField()),
                ('task_type', models.CharField(choices=[('train', 'train'), ('test', 'test'), ('custom_pqc', 'custom_pqc')], max_length=15)),
                ('task_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='trainjob',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
